name: "Notify Telegram on Commit"

on:
  push:
    branches:
      - main

jobs:
  telegram:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram Message
        run: |
          MSG="Коммит в $GITHUB_REPOSITORY от ${{ github.actor }}: ${{ github.event.head_commit.message }}"
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TG_BOT_TOKEN }}/sendMessage" \
            -d chat_id="${{ secrets.TG_CHAT_ID }}" \
            -d text="$MSG"


